### PR TITLE
added husky and configured it for required workflow

### LINKED ISSUE #145: Add husky for running scripts before committing
**Is your feature request related to a problem? Please describe.**
Right now when we commit a change and a make a PR, sometimes we forget to lint and test the code by running the scripts.

**Describe the solution you'd like**
We can add a new package called husky which will automatically run the scripts when a user tries to commit a change locally

### PR DESCRIPTION
**Pull request by Neelterminusdb**
closes #145 

Signed-off-by: NeelParihar <neel@terminusdb.com>

### CODE REVIEW

**Comment by spl** [comment]
Can you update the `README.md` with instructions on how to use it?

**Comment by Neelterminusdb** [comment]
It says that it automatically sets up husky when someone clones the repo and installs packages(Which i tested now and is working correct) so i don't think there is any other extra step which needs to be done by user

**Comment by Neelterminusdb** [comment]
And for someone who has already cloned the repo before husky implementation just need to run `npm run prepare` command to set it up

**Comment by spl** [comment]
You're right in that the user doesn't need to take active steps to use it. But I've encountered this before and was surprised and confused by it. It's not the normal procedure for everybody who might be working on this repo.

I don't want other people to have the same reaction that I did, so I think it would be good if the `README.md` gave a brief description of what happens when they do `npm install` and that `git commit` with do something before it's usual operation. It should link to [Husky](https://typicode.github.io/husky/) as well.

**Review by spl — APPROVED** [review]

**Pull request merged**
